### ISSUE TITLE
Deploy from meteor branch

### ISSUE THREAD

**Issue by mpaddock** [UK-AS-HIVE/HIVE-CI#6]
Make sure builds are pushed to dev server.

**Comment by noahadler** [comment]
Mostly done, but restarts are not done correctly.  Jon will join us today and discuss how we could use Puppet or other devops tools to improve this process.

**Comment by noahadler** [comment]
Something about forever seems to not be working quite right.  Maybe we need to add/replace it with nodemon or something else, to get better behavior.  In any case, sometimes right now it seems to stall out and require a manual stop/start on the init script.
